In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [1]:
!pip install torchaudio==0.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
import os
import subprocess
train_path = "/content/train"
test_path = "/content/test"
cache_file = "/content/audio.cache"    
cache_file_on_drive = "/content/drive/MyDrive/데이터분석/2_수도관누수데이터/cache/audio.cache"

if os.path.isdir(train_path) == False:
    subprocess.run(["unzip", "-qq", "/content/drive/MyDrive/데이터분석/dataset.zip", "-d", "/content"])

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 2.9 MB 36.4 MB/s 


In [2]:
import os
import time
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import Dataset
import torchaudio
import numpy as np
from sklearn.metrics import f1_score, confusion_matrix
import torchvision.models as models
import librosa
import pandas as pd
from torch._utils import _accumulate
from torch import default_generator, randperm
import random
from tqdm import tqdm
#import pickle
#import shutil
import subprocess
import logging
import argparse

logger = logging.getLogger('train_log')

In [3]:
class SoundDataset(Dataset):
    
    def __init__(self, dataset_path, is_train = True, use_cache = False, cache_file="/content/sound_data.cache", save_cache_file="/content/sound_data.cache"):
    #initialize lists to hold file names, labels, and folder numbers
        self.file_names = []
        self.file_path = []
        self.labels = []
        self.file_names, self.file_path, self.labels = self._getfile_list(dataset_path)
        self.idx_to_label, self.labels_idx = np.unique(self.labels, return_inverse=True)
        self.is_train = is_train
        self.data = []
        self.use_cache = use_cache

        if self.use_cache == True:

            print("Loading dataset into memory..")
            for index in tqdm(range(len(self.file_path))):
                self.data.append(self._cache(index))
            
            # if os.path.isfile(cache_file):
            #     with open(cache_file, "rb") as file:
            #         print("Loading cache dataset : {}".format(cache_file))
            #         self.data = pickle.load(file)
            # else:
            #     print("Loading dataset into memory..")
            #     for index in tqdm(range(len(self.file_path))):
            #         self.data.append(self._cache(index))

            #     print("Saving cache to file.. {}".format(cache_file))
            #     with open(cache_file, "wb") as file:
            #         pickle.dump(self.data, file)    
            
        

    def _cache(self, index):
        path = self.file_path[index]
        waveform, sample = torchaudio.load(path)

        if self.is_train:
            self.transform = transform=transforms.Compose([
                    transforms.Resize((224,224)),
                    #transforms.RandomHorizontalFlip()
            ])
        else:
            self.transform = transform=transforms.Compose([
                    transforms.Resize((224,224))
            ])

        waveform = waveform[0,int(sample/5):len(waveform) - int(sample/5)]

        # w1 = waveform.clone()
        # w2 = waveform.clone()

        # w1[w1 <= 0.015] = 0.00
        # w2[w2 >= -0.015] = 0.00
        # f_waveform = w1 + w2

        # waveform[waveform > 0.015] = 0.00
        # waveform[waveform < -0.015] = 0.00

        #waveform = torchaudio.functional.filtering.vad(waveform, sample_rate=sample, noise_reduction_amount= 3)[0]

        specgram1 = torchaudio.transforms.Spectrogram()(waveform)
        specgram1 = self._normalize(specgram1).unsqueeze(dim=0)
        specgram1 = self.transform(specgram1).squeeze(dim=0)

        waveform2 = torchaudio.functional.gain(waveform, gain_db=500.0)
        waveform2 = torchaudio.transforms.MuLawEncoding()(waveform2).float()
        specgram2 = torchaudio.transforms.Spectrogram()(waveform2)
        specgram2 = self._normalize(specgram2).unsqueeze(dim=0)
        specgram2 = self.transform(specgram2).squeeze(dim=0)

        # waveform2 = torchaudio.functional.filtering.vad(waveform.unsqueeze(dim=0), sample_rate=sample, noise_reduction_amount= 1.5)[0]
        # specgram2 = torchaudio.transforms.Spectrogram()(waveform2)
        # specgram2 = self._normalize(specgram2).unsqueeze(dim=0)
        # specgram2 = self.transform(specgram2).squeeze(dim=0)
      
        waveform3 = waveform.numpy()
        specgram3 = np.abs(librosa.stft(waveform3, n_fft=1024, hop_length=512))
        specgram3 = librosa.amplitude_to_db(specgram3, ref=np.max)
        specgram3 = torch.tensor(specgram3)
        specgram3 = self._normalize(specgram3).unsqueeze(dim=0)
        specgram3 = self.transform(specgram3).squeeze(dim=0)

        #specgram4 = torchaudio.transforms.MelSpectrogram(sample_rate=sample, n_fft=1024, n_mels=512)(waveform)
        specgram4 = torchaudio.transforms.MelSpectrogram(sample_rate=sample, n_fft=1024, n_mels=64)(waveform)
        specgram4 = self._normalize(specgram4).unsqueeze(dim=0)
        specgram4 = self.transform(specgram4).squeeze(dim=0)

        waveform5 = waveform.numpy()
        specgram5 = librosa.feature.mfcc(waveform5, sr=sample, n_mfcc = 224)
        specgram5 = torch.tensor(specgram5)
        specgram5 = self._normalize(specgram5).unsqueeze(dim=0)
        specgram5 = self.transform(specgram5).squeeze(dim=0)

        #specgram = torch.stack([specgram1,specgram2,specgram3], dim=0)

        

        # specgram4 = torchaudio.transforms.Spectrogram()(f_waveform)
        # specgram4 = self._normalize(specgram4).unsqueeze(dim=0)
        # specgram4 = self.transform(specgram4).squeeze(dim=0)

        # waveform5 = torchaudio.functional.gain(f_waveform, gain_db=500.0)
        # waveform5 = torchaudio.transforms.MuLawEncoding()(waveform5).float()
        # specgram5 = torchaudio.transforms.Spectrogram()(waveform5)
        # specgram5 = self._normalize(specgram5).unsqueeze(dim=0)
        # specgram5 = self.transform(specgram5).squeeze(dim=0)
      
        # waveform6 = f_waveform.numpy()
        # specgram6 = np.abs(librosa.stft(waveform6, n_fft=1024, hop_length=512))
        # specgram6 = librosa.amplitude_to_db(specgram6, ref=np.max)
        # specgram6 = torch.tensor(specgram6)
        # specgram6 = self._normalize(specgram6).unsqueeze(dim=0)
        # specgram6 = self.transform(specgram6).squeeze(dim=0)

        specgram = torch.stack([specgram1,specgram2, specgram3,specgram4,specgram5], dim=0)

        return specgram

    def train(self):
        self.is_train = True

    def eval(self):
        self.is_train = False

    def _getfile_list(self, path, parent=""):
        file_paths = []
        file_names = []
        labels = []
        for filename in os.listdir(path):
            fullpath = os.path.join(path, filename)
            if os.path.isfile(fullpath):
                if (parent is ""): parent = "None"
                file_paths.append(fullpath)
                file_names.append(filename)
                labels.append(parent)
            else:
                f, p, l = self._getfile_list(fullpath, filename)
                file_names += f
                file_paths += p
                labels += l
        return file_names, file_paths, labels
    
    def _normalize(self, tensor):
        tensor_minusmean = tensor - tensor.mean()
        return tensor_minusmean/tensor_minusmean.abs().max()
    
    
    def __getitem__(self, index):
        data = None
        if self.use_cache:
            data = self.data[index]
        else:
            data = self._cache(index)

        return data, self.file_names[index], self.labels_idx[index]

    def __len__(self):
        return len(self.file_names)

In [4]:
def print_log(text):
    logger.info(text)

def count_collect(output, target):
    ret = 0
    with torch.no_grad():
        ret = (output.round() == target).sum().float()
    return ret


def train(start_time, model, epoch, loader):
    model.train()
    aucc = .0

    y_true = []
    y_pred = []
    total_loss= .0

    for batch_idx, (data, filename, target) in enumerate(loader):
        optimizer.zero_grad()
        data = data.to(device)
        target = target.to(device).float()
        data = data.requires_grad_() #set requires_grad to True for training
        output = model(data)
        output = output.squeeze(dim=1)
        # target = target.unsqueeze(dim=1)
        loss = criterion(output, target) #the loss functions expects a batchSizex10 input
        loss.backward()
        optimizer.step()

        total_loss += loss
        
        output = torch.sigmoid(output)
        aucc = count_collect(output, target)
        y_true += target.int().tolist()
        y_pred += output.round().int().tolist()

        
        print('\r{:.1f}s, Train Epoch: {} (Step {}/{}) [{}]\tLoss: {:.6f}\tAucc: {:.4f}'.format(
            time.time()-start_time,
            epoch, 
            batch_idx+1, len(loader),
            len(loader.dataset), loss, aucc/len(target)), end="")
        
    f1 = f1_score(y_true, y_pred)
    total_loss/=len(loader)
    
    log = '\r{:.1f}s, Train Epoch: {} [{}]\tLoss: {:.6f}\tf1: {:.4f}'.format(
        time.time()-start_time,
        epoch, 
        len(loader.dataset),
        total_loss,
        f1)
    print_log(log)
            
def val(start_time, model, epoch, loader, std = 0.5):
    model.eval()
    aucc = .0
    loss = .0
    y_true = []
    y_pred = []
    f1 = .0
    leak_loss= .0
    leak_cnt = 0
    with torch.no_grad():
        for batch_idx, (data, filename, target) in enumerate(loader):
            data = data.to(device)
            target = target.to(device).float()
            output = model(data)
            output = output.squeeze(dim=1)
            # target = target.unsqueeze(dim=1)
            #loss += criterion(output, target) #the loss functions expects a batchSizex10 input
            
            cur_loss= criterion(output, target) #the loss functions expects a batchSizex10 input
            if target[0] == 0.:
                leak_loss += cur_loss
                leak_cnt += 1
            loss += cur_loss

            output = torch.sigmoid(output)
            aucc += count_collect(output, target)
            y_true += target.int().tolist()
            y_pred += output.round().int().tolist()

        f1 = f1_score(y_true, y_pred)
        loss/=len(loader)
        leak_loss/=leak_cnt

        log = '{:.1f}s, Val Epoch: {} [{}]\tLoss: {:.6f}\tleak_loss: {:.6f}\tAucc: {:.4f}\tf1: {:.4f}'.format(
            time.time()-start_time,
            epoch, 
            len(loader.dataset),
            loss,
            leak_loss,
            aucc/len(loader.dataset),
            f1)
        print_log(log)
        log = confusion_matrix(y_true, y_pred)
        print_log(log)

    return loss, leak_loss, f1
        
def test(model, test_path = "./test/", label = ["1", "0"]):
    ret = []
    model.eval()
    dataset = SoundDataset(test_path, is_train=False)
    loader = torch.utils.data.DataLoader(dataset, batch_size = 1)
    with torch.no_grad():
        for batch_idx, (data, filename, target) in enumerate(loader):
            data = data.to(device)
            target = target.to(device).float()
            output = model(data)
            output = torch.sigmoid(output).round()
            ret.append((filename[0], label[output.squeeze(1).squeeze().int()]))
    return ret 

def seed_worker(worker_id):
    worker_seed = torch.initial_seed() % 2**32
    np.random.seed(worker_seed)
    random.seed(worker_seed)

def splitSubset(dataset, validation_length=[120,100]):
    leak = []
    normal = []
    for idx, label in enumerate(dataset.labels):
        if label == "leak":
            leak.append(idx)
        else:
            normal.append(idx)
        
    # leak_indices = randperm(sum([len(leak)]), generator=default_generator).tolist()
    # normal_indices = randperm(sum([len(normal)]), generator=default_generator).tolist()

    t_normal = normal[0:len(normal) - validation_length[0]]
    v_normal = normal[len(normal) - validation_length[0]:]

    t_leak = leak[0:len(leak) - validation_length[1]]
    v_leak = leak[len(leak) - validation_length[1]:]


    rate = int(len(normal) / len(leak)) + 3
    normal_size = int(len(normal) / rate) 

    print("trainset - {} normal : {} leak".format(normal_size, len(t_leak)))

    train = []
    offset = 0
    for no in range(rate):
        train_list= None
        if no + 1 == rate:
            train_list= t_normal[(normal_size * no):] + t_leak
        else:
            train_list= t_normal[(normal_size * no):(normal_size * (no+1))] + t_leak
        train.append(torch.utils.data.Subset(dataset, train_list))

    vaildation_list = v_normal + v_leak
    vaildation = torch.utils.data.Subset(dataset, vaildation_list)
    return train, vaildation

# def splitSubset(dataset, validation_length=[120,100]):
#     leak = []
#     normal = []
#     for idx, label in enumerate(dataset.labels):
#         if label == "leak":
#             leak.append(idx)
#         else:
#             normal.append(idx)
        
#     leak_indices = randperm(sum([len(leak)]), generator=default_generator).tolist()
#     normal_indices = randperm(sum([len(normal)]), generator=default_generator).tolist()
    
#     #train = normal[0:len(normal_indices) - validation_length[0]] + leak[0:len(leak_indices) - validation_length[1]]

#     train = normal[0:len(leak_indices) - validation_length[1]] + leak[0:len(leak_indices) - validation_length[1]]

#     vaildation = normal[len(normal_indices) - validation_length[0]:] + leak[len(leak_indices) - validation_length[1]:]
#     return  [torch.utils.data.Subset(dataset, train), torch.utils.data.Subset(dataset, vaildation)]

In [7]:
# parser = argparse.ArgumentParser(description='Process some integers.')
# parser.add_argument('--seed', dest='random_seed', type=int, default=45)
# parser.add_argument('--lr', dest='lr', type=float, default=0.01)
# parser.add_argument('--epochs', dest='epochs', type=int, default=50)
# parser.add_argument('--step_size', dest='step_size', type=int, default=20)
# parser.add_argument('--weight_decay', dest='weight_decay', type=float, default=0.9)
# parser.add_argument('--pretrained', dest='pretrained', type=bool, default=False)
# args = parser.parse_args()
# print_log(args)

# random_seed = args.random_seed
# epochs = args.epochs
# step_size = args.step_size
# lr = args.lr
# pretrained = args.pretrained
# weight_decay = args.weight_decay

random_seed =45
epochs = 50
step_size = 20
lr = 0.01
pretrained = False
weight_decay = 0.9

random.seed(random_seed)
np.random.seed(random_seed)
torch.manual_seed(random_seed)
torch.cuda.manual_seed(random_seed)
torch.cuda.manual_seed_all(random_seed) # if use multi-GPU

g = torch.Generator()
g.manual_seed(random_seed)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

train_path = "/content/train"
test_path = "/content/test"
cache_file = "/content/audio.cache"
cache_file_on_drive = "/content/drive/MyDrive/데이터분석/2_수도관누수데이터/cache/audio.cache"

if os.path.isdir(train_path) == False:
    subprocess.run(["unzip", "-qq", "/content/drive/MyDrive/데이터분석/dataset.zip", "-d", "/content"])

# if os.path.isfile(cache_file_on_drive) and os.path.isfile(cache_file) == False:
#     shutil.copyfile(cache_file_on_drive, cache_file)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

# 모델 설정
model = models.resnet18(pretrained=pretrained)
num_f = model.fc.in_features
model.fc = nn.Linear(num_f, 1)
model.conv1 = nn.Conv2d(5, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
model = model.to(device)

# 데이터셋 로드
dataset = SoundDataset(train_path, use_cache=True, cache_file=cache_file, save_cache_file=cache_file_on_drive)
#train_set, val_set = torch.utils.data.random_split(dataset, [len(dataset)-1000, 1000])

train_set_list, val_set = splitSubset(dataset, validation_length = [200,300]) # [normal, leak]
trn_loaders = []

for sub in train_set_list:
    # 
    
    loader = torch.utils.data.DataLoader(sub, batch_size = 256, shuffle = True, worker_init_fn=seed_worker) # resnet18 best : 256  , generator=g
    trn_loaders.append(loader)

#trn_loader = torch.utils.data.DataLoader(train_set, batch_size = 256, shuffle = True)
val_loader = torch.utils.data.DataLoader(val_set, batch_size = 1)


# 모델 학습습 로깅깅 설정
start_time = time.time()

model_save_path = "/content/drive/MyDrive/데이터분석/2_수도관누수데이터/model/{:.0f}/".format(start_time)

if not os.path.exists(model_save_path):
    os.makedirs(model_save_path)

logger.setLevel(logging.INFO)
ch = logging.StreamHandler()
ch.setLevel(logging.INFO)

fh = logging.FileHandler(filename="{}train.log".format(model_save_path))
fh.setLevel(logging.INFO)
logger.addHandler(ch)
logger.addHandler(fh)

# 모델델 학습습 시작
patience = 10
best_loss = 10.0
best_f1 = .0
stop_count = 0

optimizer = optim.AdamW(model.parameters(), lr = lr, weight_decay = weight_decay)
#optimizer = optim.SGD(model.parameters(), lr = lr, momentum=0.9)
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size = step_size, gamma = 0.1)
#scheduler = optim.lr_scheduler.CyclicLR(optimizer, base_lr=0.001, max_lr=0.1, step_size_up=20, step_size_down=None, mode='exp_range', gamma=0.995)


criterion = torch.nn.BCEWithLogitsLoss()

trn_loader_size = len(trn_loaders)
for epoch in range(1, epochs+1):
    dataset.train()
    train(start_time, model, epoch, trn_loaders[epoch % trn_loader_size])
    dataset.eval()
    loss, leak_loss, f1 = val(start_time, model,epoch, val_loader)

    scheduler.step()
    
    if step_size == epoch:
        print("First round of training complete. Setting learn rate to 0.0001.")
    
    if best_loss > loss:
        model_path = os.path.join(model_save_path, "loss_{}_{:.4f}.pt".format(epoch, loss))
        torch.save(model.state_dict(), model_path)

        print_log("Save model : {}".format(model_path))
        best_loss = loss
        stop_count = 0
    elif best_loss + 0.5 < loss:
        stop_count += 1
    else:
        stop_count = 0

    if best_f1 < f1:
        best_f1 = f1
        model_path = os.path.join(model_save_path, "f1_{}_{:.4f}.pt".format(epoch, best_f1))
        torch.save(model.state_dict(), model_path)
        print_log("Save model : {}".format(model_path))
    
    if stop_count >= patience:
        print_log("EarlyStop")
        model_path = os.path.join(model_save_path, "{}_{:.4f}_last.pt".format(epoch, loss))
        torch.save(model.state_dict(), model_path)
        break
        
print_log("{:.1f}, Done".format(time.time()-start_time))  

cuda
Loading dataset into memory..


100%|██████████| 6766/6766 [04:29<00:00, 25.14it/s]


trainset - 861 normal : 1296 leak
10.7s, Train Epoch: 1 (Step 8/9) [2157]	Loss: 0.536055	Aucc: 0.7266

11.1s, Train Epoch: 1 [2157]	Loss: 0.905619	f1: 0.6292


11.1s, Train Epoch: 1 (Step 9/9) [2157]	Loss: 0.434191	Aucc: 0.7798

15.6s, Val Epoch: 1 [500]	Loss: 8.777154	leak_loss: 0.025011	Aucc: 0.6960	f1: 0.4154
[[294   6]
 [146  54]]
Save model : /content/drive/MyDrive/데이터분석/2_수도관누수데이터/model/1636693759/loss_1_8.7772.pt
Save model : /content/drive/MyDrive/데이터분석/2_수도관누수데이터/model/1636693759/f1_1_0.4154.pt


22.5s, Train Epoch: 2 (Step 8/9) [2157]	Loss: 0.410541	Aucc: 0.7891

22.8s, Train Epoch: 2 [2157]	Loss: 0.421775	f1: 0.7758


22.8s, Train Epoch: 2 (Step 9/9) [2157]	Loss: 0.373134	Aucc: 0.8440

27.9s, Val Epoch: 2 [500]	Loss: 1.009822	leak_loss: 0.088135	Aucc: 0.8140	f1: 0.7289
[[282  18]
 [ 75 125]]
Save model : /content/drive/MyDrive/데이터분석/2_수도관누수데이터/model/1636693759/loss_2_1.0098.pt
Save model : /content/drive/MyDrive/데이터분석/2_수도관누수데이터/model/1636693759/f1_2_0.7289.pt


34.8s, Train Epoch: 3 (Step 8/9) [2157]	Loss: 0.368662	Aucc: 0.8438

35.2s, Train Epoch: 3 [2157]	Loss: 0.376706	f1: 0.8028


35.2s, Train Epoch: 3 (Step 9/9) [2157]	Loss: 0.387704	Aucc: 0.8165

40.0s, Val Epoch: 3 [500]	Loss: 0.490458	leak_loss: 0.693865	Aucc: 0.7820	f1: 0.7771
[[201  99]
 [ 10 190]]
Save model : /content/drive/MyDrive/데이터분석/2_수도관누수데이터/model/1636693759/loss_3_0.4905.pt
Save model : /content/drive/MyDrive/데이터분석/2_수도관누수데이터/model/1636693759/f1_3_0.7771.pt


47.0s, Train Epoch: 4 (Step 8/9) [2157]	Loss: 0.358007	Aucc: 0.8320

47.4s, Train Epoch: 4 [2157]	Loss: 0.374824	f1: 0.7908


47.4s, Train Epoch: 4 (Step 9/9) [2157]	Loss: 0.408035	Aucc: 0.8257

52.0s, Val Epoch: 4 [500]	Loss: 1.004952	leak_loss: 1.618819	Aucc: 0.4100	f1: 0.5755
[[  5 295]
 [  0 200]]


57.5s, Train Epoch: 5 (Step 7/8) [1961]	Loss: 0.364514	Aucc: 0.8516

58.0s, Train Epoch: 5 [1961]	Loss: 0.345677	f1: 0.7979


58.0s, Train Epoch: 5 (Step 8/8) [1961]	Loss: 0.328256	Aucc: 0.8876

62.5s, Val Epoch: 5 [500]	Loss: 0.829597	leak_loss: 1.293107	Aucc: 0.4700	f1: 0.5979
[[ 38 262]
 [  3 197]]


68.7s, Train Epoch: 6 (Step 8/9) [2157]	Loss: 0.341567	Aucc: 0.8555

69.1s, Train Epoch: 6 [2157]	Loss: 0.340799	f1: 0.8248


69.1s, Train Epoch: 6 (Step 9/9) [2157]	Loss: 0.403155	Aucc: 0.8349

73.5s, Val Epoch: 6 [500]	Loss: 1.331769	leak_loss: 2.178039	Aucc: 0.4000	f1: 0.5714
[[  0 300]
 [  0 200]]


79.7s, Train Epoch: 7 (Step 8/9) [2157]	Loss: 0.393272	Aucc: 0.8398

80.1s, Train Epoch: 7 [2157]	Loss: 0.326936	f1: 0.8192


80.1s, Train Epoch: 7 (Step 9/9) [2157]	Loss: 0.310020	Aucc: 0.8716

84.6s, Val Epoch: 7 [500]	Loss: 1.321429	leak_loss: 2.153390	Aucc: 0.4000	f1: 0.5714
[[  0 300]
 [  0 200]]


90.8s, Train Epoch: 8 (Step 8/9) [2157]	Loss: 0.264905	Aucc: 0.8906

91.2s, Train Epoch: 8 [2157]	Loss: 0.327640	f1: 0.8211


91.2s, Train Epoch: 8 (Step 9/9) [2157]	Loss: 0.317224	Aucc: 0.8716

95.6s, Val Epoch: 8 [500]	Loss: 1.184419	leak_loss: 1.919192	Aucc: 0.4000	f1: 0.5714
[[  0 300]
 [  0 200]]


101.8s, Train Epoch: 9 (Step 8/9) [2157]	Loss: 0.376416	Aucc: 0.8125

102.2s, Train Epoch: 9 [2157]	Loss: 0.306850	f1: 0.8390


102.2s, Train Epoch: 9 (Step 9/9) [2157]	Loss: 0.314607	Aucc: 0.8532

107.1s, Val Epoch: 9 [500]	Loss: 1.159125	leak_loss: 1.879447	Aucc: 0.4000	f1: 0.5714
[[  0 300]
 [  0 200]]


113.3s, Train Epoch: 10 (Step 8/9) [2157]	Loss: 0.340916	Aucc: 0.8555

113.6s, Train Epoch: 10 [2157]	Loss: 0.330447	f1: 0.8173


113.6s, Train Epoch: 10 (Step 9/9) [2157]	Loss: 0.323215	Aucc: 0.8624

118.1s, Val Epoch: 10 [500]	Loss: 0.740838	leak_loss: 1.146992	Aucc: 0.4880	f1: 0.6062
[[ 47 253]
 [  3 197]]


123.5s, Train Epoch: 11 (Step 7/8) [1961]	Loss: 0.300788	Aucc: 0.8828

124.1s, Train Epoch: 11 [1961]	Loss: 0.316918	f1: 0.8021


124.0s, Train Epoch: 11 (Step 8/8) [1961]	Loss: 0.282857	Aucc: 0.8580

128.5s, Val Epoch: 11 [500]	Loss: 0.851102	leak_loss: 1.336474	Aucc: 0.4120	f1: 0.5764
[[  6 294]
 [  0 200]]


134.7s, Train Epoch: 12 (Step 8/9) [2157]	Loss: 0.325698	Aucc: 0.8594

135.1s, Train Epoch: 12 [2157]	Loss: 0.311668	f1: 0.8358


135.0s, Train Epoch: 12 (Step 9/9) [2157]	Loss: 0.346386	Aucc: 0.8440

139.5s, Val Epoch: 12 [500]	Loss: 1.209150	leak_loss: 1.977947	Aucc: 0.4000	f1: 0.5714
[[  0 300]
 [  0 200]]


145.7s, Train Epoch: 13 (Step 8/9) [2157]	Loss: 0.306439	Aucc: 0.8633

146.0s, Train Epoch: 13 [2157]	Loss: 0.302833	f1: 0.8370


146.0s, Train Epoch: 13 (Step 9/9) [2157]	Loss: 0.342061	Aucc: 0.8349

150.7s, Val Epoch: 13 [500]	Loss: 0.718170	leak_loss: 1.104765	Aucc: 0.5180	f1: 0.6228
[[ 60 240]
 [  1 199]]


156.9s, Train Epoch: 14 (Step 8/9) [2157]	Loss: 0.305642	Aucc: 0.8672

157.3s, Train Epoch: 14 [2157]	Loss: 0.314771	f1: 0.8362


157.3s, Train Epoch: 14 (Step 9/9) [2157]	Loss: 0.385104	Aucc: 0.8073

161.7s, Val Epoch: 14 [500]	Loss: 1.099839	leak_loss: 1.760577	Aucc: 0.4000	f1: 0.5714
[[  0 300]
 [  0 200]]


167.9s, Train Epoch: 15 (Step 8/9) [2157]	Loss: 0.273907	Aucc: 0.8750

168.2s, Train Epoch: 15 [2157]	Loss: 0.287264	f1: 0.8384


168.2s, Train Epoch: 15 (Step 9/9) [2157]	Loss: 0.216618	Aucc: 0.9083

172.7s, Val Epoch: 15 [500]	Loss: 0.561262	leak_loss: 0.833758	Aucc: 0.7600	f1: 0.7619
[[188 112]
 [  8 192]]


178.9s, Train Epoch: 16 (Step 8/9) [2157]	Loss: 0.333520	Aucc: 0.8594

179.3s, Train Epoch: 16 [2157]	Loss: 0.325315	f1: 0.8219


179.3s, Train Epoch: 16 (Step 9/9) [2157]	Loss: 0.397442	Aucc: 0.8440

184.2s, Val Epoch: 16 [500]	Loss: 0.822701	leak_loss: 1.312512	Aucc: 0.5460	f1: 0.6368
[[ 74 226]
 [  1 199]]


189.6s, Train Epoch: 17 (Step 7/8) [1961]	Loss: 0.312557	Aucc: 0.8789

190.1s, Train Epoch: 17 [1961]	Loss: 0.305102	f1: 0.8198


190.1s, Train Epoch: 17 (Step 8/8) [1961]	Loss: 0.303305	Aucc: 0.8580

194.5s, Val Epoch: 17 [500]	Loss: 0.424509	leak_loss: 0.493157	Aucc: 0.8480	f1: 0.8233
[[247  53]
 [ 23 177]]
Save model : /content/drive/MyDrive/데이터분석/2_수도관누수데이터/model/1636693759/loss_17_0.4245.pt
Save model : /content/drive/MyDrive/데이터분석/2_수도관누수데이터/model/1636693759/f1_17_0.8233.pt


201.6s, Train Epoch: 18 (Step 8/9) [2157]	Loss: 0.309164	Aucc: 0.8750

202.0s, Train Epoch: 18 [2157]	Loss: 0.310523	f1: 0.8283


202.0s, Train Epoch: 18 (Step 9/9) [2157]	Loss: 0.245050	Aucc: 0.9083

206.5s, Val Epoch: 18 [500]	Loss: 0.473226	leak_loss: 0.643701	Aucc: 0.8000	f1: 0.7899
[[212  88]
 [ 12 188]]


212.7s, Train Epoch: 19 (Step 8/9) [2157]	Loss: 0.267962	Aucc: 0.9062

213.0s, Train Epoch: 19 [2157]	Loss: 0.306288	f1: 0.8417


213.0s, Train Epoch: 19 (Step 9/9) [2157]	Loss: 0.371510	Aucc: 0.8532

217.9s, Val Epoch: 19 [500]	Loss: 0.682667	leak_loss: 1.058054	Aucc: 0.5760	f1: 0.6525
[[ 89 211]
 [  1 199]]


224.1s, Train Epoch: 20 (Step 8/9) [2157]	Loss: 0.339285	Aucc: 0.8555

224.5s, Train Epoch: 20 [2157]	Loss: 0.296455	f1: 0.8384


224.5s, Train Epoch: 20 (Step 9/9) [2157]	Loss: 0.229349	Aucc: 0.9450

229.1s, Val Epoch: 20 [500]	Loss: 1.348745	leak_loss: 2.228378	Aucc: 0.4220	f1: 0.5806
[[ 11 289]
 [  0 200]]


First round of training complete. Setting learn rate to 0.0001.
235.3s, Train Epoch: 21 (Step 8/9) [2157]	Loss: 0.348162	Aucc: 0.8398

235.6s, Train Epoch: 21 [2157]	Loss: 0.290651	f1: 0.8407


235.6s, Train Epoch: 21 (Step 9/9) [2157]	Loss: 0.295784	Aucc: 0.8716

240.1s, Val Epoch: 21 [500]	Loss: 0.541492	leak_loss: 0.817119	Aucc: 0.7600	f1: 0.7628
[[187 113]
 [  7 193]]


246.3s, Train Epoch: 22 (Step 8/9) [2157]	Loss: 0.254625	Aucc: 0.9102

246.7s, Train Epoch: 22 [2157]	Loss: 0.295034	f1: 0.8418


246.7s, Train Epoch: 22 (Step 9/9) [2157]	Loss: 0.318413	Aucc: 0.8624

251.2s, Val Epoch: 22 [500]	Loss: 0.338318	leak_loss: 0.387450	Aucc: 0.8660	f1: 0.8401
[[257  43]
 [ 24 176]]
Save model : /content/drive/MyDrive/데이터분석/2_수도관누수데이터/model/1636693759/loss_22_0.3383.pt
Save model : /content/drive/MyDrive/데이터분석/2_수도관누수데이터/model/1636693759/f1_22_0.8401.pt


257.3s, Train Epoch: 23 (Step 7/8) [1961]	Loss: 0.278810	Aucc: 0.8750

257.8s, Train Epoch: 23 [1961]	Loss: 0.265332	f1: 0.8357


257.8s, Train Epoch: 23 (Step 8/8) [1961]	Loss: 0.253080	Aucc: 0.8935

262.5s, Val Epoch: 23 [500]	Loss: 0.425399	leak_loss: 0.592064	Aucc: 0.8360	f1: 0.8194
[[232  68]
 [ 14 186]]


268.7s, Train Epoch: 24 (Step 8/9) [2157]	Loss: 0.243660	Aucc: 0.9062

269.0s, Train Epoch: 24 [2157]	Loss: 0.270197	f1: 0.8484


269.0s, Train Epoch: 24 (Step 9/9) [2157]	Loss: 0.224614	Aucc: 0.9266

273.5s, Val Epoch: 24 [500]	Loss: 0.317102	leak_loss: 0.302086	Aucc: 0.8680	f1: 0.8358
[[266  34]
 [ 32 168]]
Save model : /content/drive/MyDrive/데이터분석/2_수도관누수데이터/model/1636693759/loss_24_0.3171.pt


279.9s, Train Epoch: 25 (Step 8/9) [2157]	Loss: 0.249520	Aucc: 0.8945

280.3s, Train Epoch: 25 [2157]	Loss: 0.255898	f1: 0.8578


280.3s, Train Epoch: 25 (Step 9/9) [2157]	Loss: 0.170526	Aucc: 0.9266

284.9s, Val Epoch: 25 [500]	Loss: 0.319798	leak_loss: 0.339513	Aucc: 0.8660	f1: 0.8401
[[257  43]
 [ 24 176]]


291.1s, Train Epoch: 26 (Step 8/9) [2157]	Loss: 0.263527	Aucc: 0.8828

291.4s, Train Epoch: 26 [2157]	Loss: 0.267619	f1: 0.8561


291.4s, Train Epoch: 26 (Step 9/9) [2157]	Loss: 0.221958	Aucc: 0.9266

295.9s, Val Epoch: 26 [500]	Loss: 0.333228	leak_loss: 0.381257	Aucc: 0.8560	f1: 0.8302
[[252  48]
 [ 24 176]]


302.2s, Train Epoch: 27 (Step 8/9) [2157]	Loss: 0.221670	Aucc: 0.9180

302.5s, Train Epoch: 27 [2157]	Loss: 0.242000	f1: 0.8749


302.5s, Train Epoch: 27 (Step 9/9) [2157]	Loss: 0.217048	Aucc: 0.9174

307.0s, Val Epoch: 27 [500]	Loss: 0.337250	leak_loss: 0.378354	Aucc: 0.8520	f1: 0.8230
[[254  46]
 [ 28 172]]


313.2s, Train Epoch: 28 (Step 8/9) [2157]	Loss: 0.301237	Aucc: 0.8789

313.6s, Train Epoch: 28 [2157]	Loss: 0.251030	f1: 0.8690


313.6s, Train Epoch: 28 (Step 9/9) [2157]	Loss: 0.224025	Aucc: 0.8991

318.0s, Val Epoch: 28 [500]	Loss: 0.435296	leak_loss: 0.608854	Aucc: 0.8260	f1: 0.8096
[[228  72]
 [ 15 185]]


323.4s, Train Epoch: 29 (Step 7/8) [1961]	Loss: 0.271044	Aucc: 0.8984

323.9s, Train Epoch: 29 [1961]	Loss: 0.241596	f1: 0.8559


323.9s, Train Epoch: 29 (Step 8/8) [1961]	Loss: 0.206983	Aucc: 0.9349

328.4s, Val Epoch: 29 [500]	Loss: 0.351228	leak_loss: 0.388253	Aucc: 0.8580	f1: 0.8281
[[258  42]
 [ 29 171]]


334.6s, Train Epoch: 30 (Step 8/9) [2157]	Loss: 0.253050	Aucc: 0.8945

335.0s, Train Epoch: 30 [2157]	Loss: 0.245469	f1: 0.8676


335.0s, Train Epoch: 30 (Step 9/9) [2157]	Loss: 0.164967	Aucc: 0.9358

339.5s, Val Epoch: 30 [500]	Loss: 0.331461	leak_loss: 0.358411	Aucc: 0.8660	f1: 0.8362
[[262  38]
 [ 29 171]]


345.6s, Train Epoch: 31 (Step 8/9) [2157]	Loss: 0.253596	Aucc: 0.9023

346.0s, Train Epoch: 31 [2157]	Loss: 0.235356	f1: 0.8761


346.0s, Train Epoch: 31 (Step 9/9) [2157]	Loss: 0.223404	Aucc: 0.8899

350.6s, Val Epoch: 31 [500]	Loss: 0.370213	leak_loss: 0.460061	Aucc: 0.8520	f1: 0.8303
[[245  55]
 [ 19 181]]


356.7s, Train Epoch: 32 (Step 8/9) [2157]	Loss: 0.209656	Aucc: 0.9102

357.1s, Train Epoch: 32 [2157]	Loss: 0.246413	f1: 0.8677


357.1s, Train Epoch: 32 (Step 9/9) [2157]	Loss: 0.220865	Aucc: 0.9266

361.5s, Val Epoch: 32 [500]	Loss: 0.352257	leak_loss: 0.400520	Aucc: 0.8400	f1: 0.8131
[[246  54]
 [ 26 174]]


367.7s, Train Epoch: 33 (Step 8/9) [2157]	Loss: 0.210502	Aucc: 0.9102

368.1s, Train Epoch: 33 [2157]	Loss: 0.219513	f1: 0.8925


368.1s, Train Epoch: 33 (Step 9/9) [2157]	Loss: 0.237809	Aucc: 0.9266

372.6s, Val Epoch: 33 [500]	Loss: 0.346780	leak_loss: 0.400842	Aucc: 0.8560	f1: 0.8294
[[253  47]
 [ 25 175]]


378.8s, Train Epoch: 34 (Step 8/9) [2157]	Loss: 0.223877	Aucc: 0.9062

379.2s, Train Epoch: 34 [2157]	Loss: 0.231893	f1: 0.8865


379.2s, Train Epoch: 34 (Step 9/9) [2157]	Loss: 0.249192	Aucc: 0.8899

383.6s, Val Epoch: 34 [500]	Loss: 0.406157	leak_loss: 0.527705	Aucc: 0.8340	f1: 0.8118
[[238  62]
 [ 21 179]]


389.0s, Train Epoch: 35 (Step 7/8) [1961]	Loss: 0.232911	Aucc: 0.9062

389.6s, Train Epoch: 35 [1961]	Loss: 0.227589	f1: 0.8608


389.6s, Train Epoch: 35 (Step 8/8) [1961]	Loss: 0.187054	Aucc: 0.9408

394.0s, Val Epoch: 35 [500]	Loss: 0.359234	leak_loss: 0.419661	Aucc: 0.8720	f1: 0.8454
[[261  39]
 [ 25 175]]
Save model : /content/drive/MyDrive/데이터분석/2_수도관누수데이터/model/1636693759/f1_35_0.8454.pt


400.5s, Train Epoch: 36 (Step 8/9) [2157]	Loss: 0.217951	Aucc: 0.9297

400.9s, Train Epoch: 36 [2157]	Loss: 0.226481	f1: 0.8900


400.8s, Train Epoch: 36 (Step 9/9) [2157]	Loss: 0.207624	Aucc: 0.9266

405.3s, Val Epoch: 36 [500]	Loss: 0.356291	leak_loss: 0.404520	Aucc: 0.8540	f1: 0.8282
[[251  49]
 [ 24 176]]


411.5s, Train Epoch: 37 (Step 8/9) [2157]	Loss: 0.196720	Aucc: 0.9180

411.9s, Train Epoch: 37 [2157]	Loss: 0.218659	f1: 0.8919


411.9s, Train Epoch: 37 (Step 9/9) [2157]	Loss: 0.189823	Aucc: 0.9174

416.3s, Val Epoch: 37 [500]	Loss: 0.360148	leak_loss: 0.424348	Aucc: 0.8480	f1: 0.8233
[[247  53]
 [ 23 177]]


422.4s, Train Epoch: 38 (Step 8/9) [2157]	Loss: 0.243876	Aucc: 0.9023

422.8s, Train Epoch: 38 [2157]	Loss: 0.217744	f1: 0.8870


422.8s, Train Epoch: 38 (Step 9/9) [2157]	Loss: 0.138648	Aucc: 0.9450

427.3s, Val Epoch: 38 [500]	Loss: 0.357965	leak_loss: 0.405319	Aucc: 0.8560	f1: 0.8318
[[250  50]
 [ 22 178]]


433.5s, Train Epoch: 39 (Step 8/9) [2157]	Loss: 0.189958	Aucc: 0.9180

433.8s, Train Epoch: 39 [2157]	Loss: 0.192376	f1: 0.9064


433.8s, Train Epoch: 39 (Step 9/9) [2157]	Loss: 0.163422	Aucc: 0.9450

438.3s, Val Epoch: 39 [500]	Loss: 0.333199	leak_loss: 0.353314	Aucc: 0.8620	f1: 0.8329
[[259  41]
 [ 28 172]]


444.5s, Train Epoch: 40 (Step 8/9) [2157]	Loss: 0.217661	Aucc: 0.9219

444.8s, Train Epoch: 40 [2157]	Loss: 0.209274	f1: 0.9029


444.8s, Train Epoch: 40 (Step 9/9) [2157]	Loss: 0.337779	Aucc: 0.8349

449.3s, Val Epoch: 40 [500]	Loss: 0.498324	leak_loss: 0.720608	Aucc: 0.8300	f1: 0.8148
[[228  72]
 [ 13 187]]


454.7s, Train Epoch: 41 (Step 7/8) [1961]	Loss: 0.160841	Aucc: 0.9414

455.3s, Train Epoch: 41 [1961]	Loss: 0.180815	f1: 0.8990


455.3s, Train Epoch: 41 (Step 8/8) [1961]	Loss: 0.199448	Aucc: 0.9112

459.7s, Val Epoch: 41 [500]	Loss: 0.412273	leak_loss: 0.542970	Aucc: 0.8400	f1: 0.8198
[[238  62]
 [ 18 182]]


465.8s, Train Epoch: 42 (Step 8/9) [2157]	Loss: 0.200897	Aucc: 0.9180

466.2s, Train Epoch: 42 [2157]	Loss: 0.173058	f1: 0.9252


466.2s, Train Epoch: 42 (Step 9/9) [2157]	Loss: 0.142693	Aucc: 0.9541

470.7s, Val Epoch: 42 [500]	Loss: 0.346000	leak_loss: 0.378775	Aucc: 0.8640	f1: 0.8373
[[257  43]
 [ 25 175]]


476.9s, Train Epoch: 43 (Step 8/9) [2157]	Loss: 0.205874	Aucc: 0.9219

477.2s, Train Epoch: 43 [2157]	Loss: 0.166540	f1: 0.9178


477.2s, Train Epoch: 43 (Step 9/9) [2157]	Loss: 0.125412	Aucc: 0.9633

481.6s, Val Epoch: 43 [500]	Loss: 0.361665	leak_loss: 0.405808	Aucc: 0.8680	f1: 0.8436
[[256  44]
 [ 22 178]]


487.8s, Train Epoch: 44 (Step 8/9) [2157]	Loss: 0.195944	Aucc: 0.9336

488.2s, Train Epoch: 44 [2157]	Loss: 0.174992	f1: 0.9169


488.1s, Train Epoch: 44 (Step 9/9) [2157]	Loss: 0.147993	Aucc: 0.9541

492.6s, Val Epoch: 44 [500]	Loss: 0.371583	leak_loss: 0.430192	Aucc: 0.8540	f1: 0.8306
[[248  52]
 [ 21 179]]


498.8s, Train Epoch: 45 (Step 8/9) [2157]	Loss: 0.139836	Aucc: 0.9492

499.2s, Train Epoch: 45 [2157]	Loss: 0.142151	f1: 0.9396


499.1s, Train Epoch: 45 (Step 9/9) [2157]	Loss: 0.119318	Aucc: 0.9725

503.6s, Val Epoch: 45 [500]	Loss: 0.352789	leak_loss: 0.378174	Aucc: 0.8560	f1: 0.8302
[[252  48]
 [ 24 176]]


509.8s, Train Epoch: 46 (Step 8/9) [2157]	Loss: 0.159091	Aucc: 0.9453

510.1s, Train Epoch: 46 [2157]	Loss: 0.158496	f1: 0.9267


510.1s, Train Epoch: 46 (Step 9/9) [2157]	Loss: 0.164958	Aucc: 0.9450

514.5s, Val Epoch: 46 [500]	Loss: 0.358976	leak_loss: 0.381017	Aucc: 0.8620	f1: 0.8353
[[256  44]
 [ 25 175]]


519.9s, Train Epoch: 47 (Step 7/8) [1961]	Loss: 0.129193	Aucc: 0.9375

520.5s, Train Epoch: 47 [1961]	Loss: 0.155598	f1: 0.9212


520.5s, Train Epoch: 47 (Step 8/8) [1961]	Loss: 0.134217	Aucc: 0.9527

524.9s, Val Epoch: 47 [500]	Loss: 0.371969	leak_loss: 0.424854	Aucc: 0.8480	f1: 0.8224
[[248  52]
 [ 24 176]]


531.1s, Train Epoch: 48 (Step 8/9) [2157]	Loss: 0.136674	Aucc: 0.9570

531.4s, Train Epoch: 48 [2157]	Loss: 0.153347	f1: 0.9362


531.4s, Train Epoch: 48 (Step 9/9) [2157]	Loss: 0.102328	Aucc: 0.9725

535.8s, Val Epoch: 48 [500]	Loss: 0.357014	leak_loss: 0.383371	Aucc: 0.8620	f1: 0.8361
[[255  45]
 [ 24 176]]


542.0s, Train Epoch: 49 (Step 8/9) [2157]	Loss: 0.182567	Aucc: 0.9375

542.4s, Train Epoch: 49 [2157]	Loss: 0.151063	f1: 0.9309


542.4s, Train Epoch: 49 (Step 9/9) [2157]	Loss: 0.115532	Aucc: 0.9633

546.8s, Val Epoch: 49 [500]	Loss: 0.374656	leak_loss: 0.419426	Aucc: 0.8580	f1: 0.8337
[[251  49]
 [ 22 178]]


553.0s, Train Epoch: 50 (Step 8/9) [2157]	Loss: 0.140674	Aucc: 0.9609

553.4s, Train Epoch: 50 [2157]	Loss: 0.159775	f1: 0.9346


553.4s, Train Epoch: 50 (Step 9/9) [2157]	Loss: 0.193347	Aucc: 0.9174

557.8s, Val Epoch: 50 [500]	Loss: 0.379903	leak_loss: 0.429977	Aucc: 0.8480	f1: 0.8241
[[246  54]
 [ 22 178]]
557.8, Done


In [9]:
#/content/drive/MyDrive/데이터분석/2_수도관누수데이터/model/1636370724/24_0.3122.pt
model.load_state_dict(torch.load("/content/drive/MyDrive/데이터분석/2_수도관누수데이터/model/1636693759/f1_35_0.8454.pt"))
ret = test(model, test_path)
df = pd.DataFrame(ret, columns=["AudioName","ClassID"])
df.to_csv("/content/drive/MyDrive/데이터분석/2_수도관누수데이터/{:0f}.csv".format(start_time), index = False)

In [ ]:
df = pd.DataFrame(ret, columns=["AudioName","ClassID"])
df.to_csv("/content/drive/MyDrive/데이터분석/2_수도관누수데이터/{:0f}.csv".format(1234), index = False)

In [24]:
#/content/drive/MyDrive/데이터분석/2_수도관누수데이터/model/1636370724/24_0.3122.pt
model.load_state_dict(torch.load("/content/drive/MyDrive/데이터분석/2_수도관누수데이터/model/1636682560/loss_24_0.3171.pt"))
ret = test(model, test_path)
df = pd.DataFrame(ret, columns=["AudioName","ClassID"])
df.to_csv("/content/drive/MyDrive/데이터분석/2_수도관누수데이터/{:0f}.csv".format(123), index = False)